### ISSUE TITLE
new feature : pass arbitrary environment variables

### ISSUE THREAD

**Issue by Kaiz3rTool** [hypothetical-inc/GafferDeadline#14]
Hello,
As Deadline is able to receive environment variable from the submitter, It can be interesting to have this ability in GafferDeadline

It can help to resolve some gaffer users problem (like me) when using environment variable to set several part of a script (example : custom boxes folders with GAFFER_REFERENCE_PATHS )
I guess that the insteresting features are : 
IncludeEnvironment=True
UseJobEnvironmentOnly=True

 more infos at : https://docs.thinkboxsoftware.com/products/deadline/10.0/1_User%20Manual/manual/environment.html

**Comment by ericmehl** [comment]
Hey @Kaiz3rTool, you read my mind actually! I've had that feature on the list of things to do for a few weeks now. I'll bump it up since you'd have a direct use for it.

**Comment by Kaiz3rTool** [comment]
ahah glad to hear it, I've give it a try but without succes... i guess I need to learn more about how deadline handle this kind of things to gives you a hand
thank you eric !

**Comment by ericmehl** [comment]
Yeah, it is definitely a lot to wrap your mind around when first getting into it. Once I get the feature added I'm happy to walk you through the changes if you would like.

**Comment by Kaiz3rTool** [comment]
would be perfect, thank you Eric

**Comment by ericmehl** [comment]
Hey @Kaiz3rTool, have a look at the release I just put up: https://github.com/hypothetical-inc/GafferDeadline/releases/tag/0.52.0.0

I added the ability to add environment variables, and also custom Deadline settings. Now you can set any Deadline submission variable! 

There are a few other updates there too :)

I will write up a bit of an explanation of how I did the environment variables (it's about the same for the Deadline variables too) in a bit - the relevant commit is this one: https://github.com/hypothetical-inc/GafferDeadline/pull/15/commits/587daf707a2015db2add00a55771aeeb8443106c

**Comment by ericmehl** [comment]
Here's a little more detail on how I approached this feature addition. Not saying it's the "right" way but since it's a relatively small addition hopefully it will be helpful if you are wanting to add something yourself. There are a few places you have to know where to look for things like setting up the plugs and setting up the job that can take a bit of time to sort out on your own.

First thing was to decide on what kind of plug I wanted to represent the data for the environment variables. I usually look through existing nodes to see if they do anything similar and in this case the SystemCommand has an exact corresponding plug for environment variables. Personally I find the ability to add data like vectors as environment variables a little odd and perhaps not intuitive, but I also am guessing most people won't even try that very much and stick to strings and numbers.

So the plugs were set up here: https://github.com/hypothetical-inc/GafferDeadline/blob/ca3ec82753d3762d61d09f4d89dc75a1d185e91a/python/GafferDeadline/DeadlineDispatcher.py#L394-L396 along with the other plugs. Note that that function is only called for setting up a new dispatcher - if you are loading an old script with command nodes it won't be added. There's almost certainly a way to add the new plugs to old scripts on load but I haven't jumped into that yet.

Luckily this change doesn't involve the dependency handling system since that's a spaghetti mess. So the second task is to take the data from the plug and add it to the job information when it's being sent to Deadline.

I represent the job in its own module https://github.com/hypothetical-inc/GafferDeadline/blob/master/python/GafferDeadline/GafferDeadlineJob.py

The changes there are in the commit https://github.com/hypothetical-inc/GafferDeadline/commit/587daf707a2015db2add00a55771aeeb8443106c#diff-0ca5ddc9ac1af30824d201b35de72b19

A dictionary is a pretty exact analog to key / value environment variables so I went with those to store the data. I'm not worried about reading them back from the job object so a function to append environment variables is sufficient for now.

Back in the [DeadlineDispatcher.py](https://github.com/hypothetical-inc/GafferDeadline/blob/master/python/GafferDeadline/DeadlineDispatcher.py#L220-L223) module the `submitDeadlineJob` function is where most of the submission work happens. The job info is assembled and handed off to the DeadlineJob object here. https://github.com/hypothetical-inc/GafferDeadline/blob/ca3ec82753d3762d61d09f4d89dc75a1d185e91a/python/GafferDeadline/DeadlineDispatcher.py#L220-L223 is where I set up the environment variables and append them to the job. The pattern for that was taken from the SystemCommand node.

The last thing to do is handle translating the job information to the format Deadline expects. That you can usually find in the Deadline documentation on the "Manual Submission" page. Deadline's system is a nice key / value setup with the addition for things like environment variables of needing a number at the end of the `EnvironmentKeyValue` to support multiple variables.
https://github.com/hypothetical-inc/GafferDeadline/blob/ca3ec82753d3762d61d09f4d89dc75a1d185e91a/python/GafferDeadline/GafferDeadlineJob.py#L233-L235

I hope that helps you for the future if you want to make customizations! I'm happy to help, and accept relevant pull requests too.

**Comment by Kaiz3rTool** [comment]
Hey Eric, 
amazing ! thank you for the efforts
I will give it a try on monday
bests

**Comment by ericmehl** [comment]
@Kaiz3rTool I just [released a fixup](https://github.com/hypothetical-inc/GafferDeadline/releases/tag/0.52.0.1) for a couple of things that you will probably want to update to if you've already downloaded the version from Thursday.
