### ISSUE TITLE
DLL error loading arnold modules

### ISSUE THREAD

**Issue by willDTF** [hypothetical-inc/GafferDeadline#57]
Hi Eric, 
starting playing with Gaffer on windows, i have some trouble to make it works with deadline

In my pipeline I have many custom plugins that gaffer loads with GAFFER_EXTENSION_PATHS variable
If i launch a script using plugins to deadline, it fails as it doesn't found the module from GAFFER_EXTENSION_PATHS (logic for now)

so in deadline environment variable, I populate with GAFFER_EXTENSION_PATHS variable list
this results :
 
`C:/Softwares/Gaffer/bin/arnold/7.2;W:/DOTHEFILM/plugins/gaffer//deadline;W:/DOTHEFILM/python/DTFplugins/gaffertools;`
![image](https://github.com/hypothetical-inc/GafferDeadline/assets/4272733/0e2727b2-e9c8-4d5c-b3a4-bd08a51ef2cc)

but when i send to deadline, it's fail as it try to load DLL files as python modules from C:/Softwares/Gaffer/bin/arnold/7.2. If i remove it, Arnold modules are missing so still cannot render

Deadline output : 

`
2023-11-09 14:12:22:  0: DEBUG: ManagedProcess.Execute: waiting for child process to exit
2023-11-09 14:12:23:  0: DEBUG: ManagedProcess.Execute: m_process.IsRunning(): True    m_process.IsStdoutAvailable(): False
2023-11-09 14:12:23:  0: DEBUG: ManagedProcess.Execute: m_process.IsRunning(): True    m_process.IsStdoutAvailable(): False
2023-11-09 14:12:24:  0: DEBUG: ManagedProcess.Execute: m_process.IsRunning(): True    m_process.IsStdoutAvailable(): False
2023-11-09 14:12:24:  0: DEBUG: ManagedProcess.HandleStdoutLine: parsing stdout: ERROR : gaffer execute : loading "C:/ProgramData/Thinkbox/Deadline10/workers/WS3/jobsData/654cda92c767e8a2943a818d/thread0_temp2Eh9h0/lookdev_Mania_TEST.gfr" : Line 1 of C:/ProgramData/Thinkbox/Deadline10/workers/WS3/jobsData/654cda92c767e8a2943a818d/thread0_temp2Eh9h0/lookdev_Mania_TEST.gfr : ModuleNotFoundError: No module named 'GafferArnold'
2023-11-09 14:12:24:  0: STDOUT: ERROR : gaffer execute : loading "C:/ProgramData/Thinkbox/Deadline10/workers/WS3/jobsData/654cda92c767e8a2943a818d/thread0_temp2Eh9h0/lookdev_Mania_TEST.gfr" : Line 1 of C:/ProgramData/Thinkbox/Deadline10/workers/WS3/jobsData/654cda92c767e8a2943a818d/thread0_temp2Eh9h0/lookdev_Mania_TEST.gfr : ModuleNotFoundError: No module named 'GafferArnold'
2023-11-09 14:12:24:  0: DEBUG: ManagedProcess.HandleStdoutLine: parsing stdout: "Error(s) running Gaffer"
2023-11-09 14:12:24:  0: STDOUT: "Error(s) running Gaffer"`

any idea how I can make it works please ? 
thanks

**Comment by willDTF** [comment]
I founded this, about how to transmit environment variable from DCC to Job, maybe it could be a great feature to add ? 
https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/manual/environment.html

**Comment by ericmehl** [comment]
> So I founded this, about how to transmit environment variable from DCC to Job, maybe it could be a great feature to add ?
> https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/manual/environment.html

That's the method Gaffer Deadline currently uses to set environment variables as you are doing in your screen capture above.

Regardless of what you set in `GAFFER_EXTENSION_PATHS`, it sounds like Gaffer is not finding Arnold when launched from Deadline. When run from Deadline, the `gaffer` / `gaffer.cmd` script needs to be launched with `ARNOLD_ROOT` set, like it does when you launch manually from a terminal.

There are at least a couple ways to do that :
1. If you are using your own launch script to set environment variables and then launch `gaffer.cmd`, you could have Deadline run that. Then you just need to make sure that script is correctly setup for the machines running on Deadline.
2. You could set `ARNOLD_ROOT` in the Gaffer Deadline environment variables, as you are doing for `GAFFER_EXTENSION_PATHS` and others in your screen capture.

An alternative to option 2 is to set `ARNOLD_ROOT` in Deadline settings to a value of `${ARNOLD_ROOT}`. Then when Gaffer Deadline is dispatching the job, it will set Deadline's `ARNOLD_ROOT` variable to whatever your current value of `ARNOLD_ROOT` is at the time of dispatch. That might be helpful if you are changing Arnold versions or running on different OS.

If you get `ARNOLD_ROOT` set for the job, does that fix the launch issue?

**Comment by ericmehl** [comment]
> I also have the problem with rendering on linux, as the variable is set in gafferdispatch.py, seems that Deadline cant edit it to make it works on linux

Double checking I understand what you're trying to accomplish - you want to submit a job from Windows and have that run a Linux machine on Deadline, correct? In that case I'm guessing your issue is mapping the path separators from `;` on Windows to `:` on Linux. Does that sound right?

I'd have to think a bit about if we should be automatically converting to and from `;` and `:` in the Gaffer Deadline plugin. It does sound helpful for this case, since it's probably common to have `GAFFER_EXTENSION_PATHS` set with multiple paths that will need the correct separator. But I'm a little wary of changing user's settings that way - some users might have reasons to not want their variables changed without them choosing.

In the Path Mapping section at the link you sent ( https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/manual/environment.html ) it describes how you can use `JobPreLoad.py` and `GlobalJobPreload.py` scripts to do your own path mapping for environment variables. That might be a good per-studio solution to keep the maximum control over how jobs are launched. You'd need to use the second version of their code snippet, where they use `incomingEnvVar = job.GetJobEnvironmentKeyValue("MY_ENV_VAR")` to get the environment variable from the job settings.

**Comment by willDTF** [comment]
hi eric, 
thank you for your help, I will keep option 2, as it gives the exact gaffer scene setup and it's work if i send from windows to windows

about second answer, yes that's exactly what I'm trying to do, as our render node is on linux only
I looked at JobPreLoad thing, i will try something on this side but i was wondering if there is a simpler method

thank you Eric !
