### ISSUE TITLE
Python 3 compatible version

### ISSUE THREAD

**Issue by willDTF** [hypothetical-inc/GafferDeadline#59]
deadline updated to python 3, making this plugin fails
i have found this to translate the plugin to python 3 https://awsthinkbox.zendesk.com/hc/en-us/articles/16540755200279-Deadline-10-3-0-9-Custom-Plugins-based-of-Python-version-less-than-3-10-will-break

**Comment by ericmehl** [comment]
This should be fixed in the latest release - https://github.com/hypothetical-inc/GafferDeadline/releases/tag/0.57.2.0. I don't have the latest Deadline installed, so I'm not sure I made the fix for Python 3.10, but the errors from Python 3 are fixed for me.

Let me know if you're still having problems with the latest Deadline and I can update to that version to sort out a fix.
