### ISSUE TITLE
GafferDeadline python dispatch

### ISSUE THREAD

**Issue by willDTF** [hypothetical-inc/GafferDeadline#87]
hi, i updated from 0.57 and now i'm not able to dispatch with python

i was used to do : 
```
__dispatcher = GafferDeadline.DeadlineDispatcher()
node=root['myRenderBox']['RENDER'] #render is GafferDeadline.DeadlineDispatcher( "RENDER" ) node
__dispatcher.dispatch([node])
```

but now it returns : 
`Gaffer.ProcessException : line 3 : DeadlineDispatcher.task : create_directory: Access is denied.: "C:\Windows\System32\004546" `

of course i dont try to render is Windows folder. any idea why it try to do something there ? 
clicking the dispatch button normally works as expected

thanks

**Comment by lattaai9** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the _doDispatch method to use a valid job directory when dispatching from Python. This fixes the issue where the dispatcher was trying to create directories in the Windows System folder.

You can review changes in this commit: https://github.com/lattaai9/hypothetical-inc-GafferDeadline-87/commit/9581ced57bf1618c8a756c3810eed0b95a501495.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ericmehl** [comment]
The latest version changed where the temporary job submission files are saved. Now you'll need to set the value of the `jobsDirectory` (and `jobName`) plugs on your newly created `__dispatcher` so it will know where to write the job submission files and what to call the job in Deadline.

If you set those plugs, does it work?

**Comment by willDTF** [comment]
thanks Eric, i guess i missed this part
